---
name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: /usr/bin/bash -l -e -o pipefail {0}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: savant setup
        run: |
          curl -O https://repository.savantbuild.org/org/savantbuild/savant-core/2.0.0-RC.8/savant-2.0.0-RC.8.tar.gz
          tar xzvf savant-2.0.0-RC.8.tar.gz
          savant-2.0.0-RC.8/bin/sb --version
          SAVANT_PATH=$(realpath -s "./savant-2.0.0-RC.8/bin")
          echo "${SAVANT_PATH}" >> $GITHUB_PATH
          mkdir -p ~/.savant/plugins
          JAVA_HOME="${JAVA_HOME_21_X64}"
          # For now, using the 21 JDK that comes on the GHA runner
          cat << EOF > ~/.savant/plugins/org.savantbuild.plugin.java.properties
          21=${JAVA_HOME}
          EOF
          echo "JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          # Groovy does not come with runners OOB
          curl -O https://groovy.jfrog.io/artifactory/dist-release-local/groovy-zips/apache-groovy-binary-4.0.22.zip
          unzip apache-groovy-binary-4.0.22.zip
          GROOVY_PATH=$(realpath -s "./groovy-4.0.22")
          cat << EOF > ~/.savant/plugins/org.savantbuild.plugin.groovy.properties
          4.0=${GROOVY_PATH}
          EOF
      # Takes some time, better to tell difference between this step and actual test run time
      - name: compile/pull Savant dependencies
        run: |
          $JAVA_HOME/bin/java -version
          sb --version
          sb clean compile
      - name: run tests/integrate
        run: |
          sb clean int
      - name: publish test report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'build/test-reports/junitreports/**/*.xml'
      - name: capture reports
        uses: actions/upload-artifact@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          name: testng_reports
          path: build/test-reports/
